project:
  type: website

website:
  title: "Ringberg 2025"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: program.qmd
        text: Program
    right:
      - href: https://www.schloss-ringberg.de/home
        text: Venue
      - href: travel.qmd
        text: Travel
      - href: contact.qmd
        text: Contact


format:
  html:
    theme: lux # flatly darkly
    toc: true